name: contextos
run-name: Aprendiendo a usar contextos

on: push
env: 
  GITHUB_REF: ${{ github.ref }}
jobs:
  check-main:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Desplegando en la rama $GITHUB_REF en el repositorio ${{ github.repository }}
