name: triggers-example
run-name: Learning actions triggers
on:
  pull_request:
    types: [updated]

  jobs:
    approved:
      if: github.event.review.state == 'approved'
      runs-on: ubuntu-latest
      steps:
        - name: created by
          run: echo "job created by ${{github.actor}}"
        - name: approved step
          run: echo "This Pr was approved"
