name: triggers-example
run-name: Learning actions triggers
on:
  pull_request:
    types: [closed]

jobs:
  approved:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: created by
        run: echo "job created by ${{github.actor}}"
      - name: approved step
        run: echo "This Pr was approved"
