name: variables
run-name: Aprendiendo variables
on: workflow_dispatch
env:
  DIA_DE_LA_SEMANA: Lunes
jobs:
  saludo-semana:
    runs-on: ubuntu-latest
    env:
      SALUDO: Hola
    steps:
      - name: Saludar
        run: echo "$SALUDO ${{ vars.CUSTOM_NAME }}. Hoy es $DIA_DE_LA_SEMANA"
        env:
          NAME: Carlos
