name: variables
run-name: Aprendiendo variables
on: workflow_dispatch
env:
  DIA_DE_LA_SEMANA: Lunes
jobs:
  saludo-semana:
    name: Saludo Normal 
    runs-on: ubuntu-latest
    env:
      SALUDO: Hola
    steps:
      - name: Saludar
        run: echo "$SALUDO ${{ vars.CUSTOM_NAME }}. Hoy es $DIA_DE_LA_SEMANA"
        env:
          NAME: Carlos
  saludo-secreto:
    name: Saludo Secreto
    runs-on: ubuntu-latest
    steps:
      - name: Saludar secretamente
        run: echo " $SALUDO ${{ vars.CUSTM_NAME }}. Tu contraseña es ${{ secrets.PASSWORD }}"
